ci: temporarily disable testing on macOS via Nix
For some reason the Rust example does not work on macOS using
a Nix environment. Not sure why as it works for everything other
environment we test. Will investigate later.

The logs are:
     Updating git repository `https://github.com/Ivan-Velickovic/rust-seL4`
    Updating crates.io index
warning: spurious network error (3 tries remaining): [35] SSL connect error (OpenSSL/3.0.12: error:16000069:STORE routines::unregistered scheme)
warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL/3.0.12: error:16000069:STORE routines::unregistered scheme)
warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL/3.0.12: error:16000069:STORE routines::unregistered scheme)
error: failed to get `cfg-if` as a dependency of package `sel4-microkit v0.1.0 (https://github.com/Ivan-Velickovic/rust-seL4?branch=dev#e4bde410)`
make: Leaving directory '/Users/runner/work/libvmm/libvmm/examples/rust'
    ... which satisfies git dependency `sel4-microkit` (locked to 0.1.0) of package `vmm v0.1.0 (/Users/runner/work/libvmm/libvmm/examples/rust)`

Caused by:
  failed to query replaced source registry `crates-io`